// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }








import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SoftSell | Empowering Your Digital Solutions",
  description: "SoftSell offers cutting-edge software solutions tailored to your business needs. Experience innovation and efficiency with our expert team.",
  keywords: ["SoftSell", "software solutions", "digital transformation", "business software", "IT services"],
  authors: [{ name: "SoftSell Team", url: "https://softsell.com" }],
  openGraph: {
    title: "SoftSell | Empowering Your Digital Solutions",
    description: "Discover how SoftSell's innovative software solutions can transform your business operations.",
    url: "https://softsell.com",
    siteName: "SoftSell",
    images: [
      {
        url: "/hero1.webp",
        width: 1200,
        height: 630,
        alt: "SoftSell - Empowering Your Digital Solutions",
      },
    ],
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <link rel="icon" href="/newLogo.png" type="image/x-icon" />
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords.join(", ")} />
        <meta name="author" content="SoftSell Team" />
        <title>{metadata.title}</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {children}
      </body>
    </html>
  );
}
